In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import matplotlib
from matplotlib import font_manager,rc
import re

matplotlib.rc('font', family = 'Malgun Gothic')

## 데이터 불러오기

- Card_ID : 카드사 고유 ID
- 분류 : 신용카드 / 체크카드 
- 혜택 분야 : 카드 혜택
- 소개 : 해당 카드 소개
- 연회비 : 카드 연회비
- 옵션 : 카드 옵션(교통기능, IC기능, 가족카드 등)
- 카드명 : 카드이름

In [2]:
Card_data=pd.read_csv("./000_Card_Data.csv")
Card_data.head()

,Card_ID,분류,혜택분야,소개,연회비,옵션,카드명
0,0,체크카드,life,한국야쿠르트와 GS리테일의 특별한 혜택 !,없음,후불교통가능\n가족카드 발급 불가,한국야쿠르트 팝 S카드 체크
1,1,체크카드,life,카카오페이로 간편하게 결제하고 혜택까지 플러스,없음,후불교통가능\n가족카드 발급 불가,카카오페이 S 체크카드(무지)
2,2,체크카드,life,속 깊은 디지털 라이프!,없음,가족카드 가능,S카드 Deep Dream 체크
3,3,체크카드,life,난치병 아이들의 꿈을 이뤄주는 기부카드,없음,후불교통가능,S카드 JYP Fan’s EDM 체크
4,4,체크카드,life,미니언즈가 다 드림!,없음,NaN,S카드 Deep Dream 체크\n(미니언즈)

In [3]:
Card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Card_ID  263 non-null    int64
 1   분류       263 non-null    object
 2   혜택분야     263 non-null    object
 3   소개       263 non-null    object
 4   연회비      263 non-null    object
 5   옵션       205 non-null    object
 6   카드명      263 non-null    object
dtypes: int64(1), object(6)
memory usage: 14.5+ KB

## 요약통계량

In [4]:
Card_data.describe()

          Card_ID
count  263.000000
mean   131.000000
std     76.065761
min      0.000000
25%     65.500000
50%    131.000000
75%    196.500000
max    262.000000

## 결측치 확인

In [5]:
Card_data.isnull().sum()

Card_ID     0
분류          0
혜택분야        0
소개          0
연회비         0
옵션         58
카드명         0
dtype: int64

> 옵션에서 결측치 확인

## 데이터 빈도 확인

In [6]:
for i in Card_data.columns:
    display(pd.DataFrame(Card_data[i].value_counts()))
    print("["+i+"]")

     Card_ID
262        1
97         1
95         1
94         1
93         1
..       ...
169        1
168        1
167        1
166        1
0          1

[263 rows x 1 columns]

[Card_ID]

       분류
신용카드  176
체크카드   87

[분류]

                혜택분야
shopping          47
public            46
life              35
oil               27
culture           25
onlineShopping    22
travel            21
comm              17
food              14
finance            9

[혜택분야]

                                                    소개
할인+적립+신한금융 서비스까지 한 번에!                               6
전월 이용 조건 없이 현장할인 3천원 서비스 제공 (1일 1회, 본인회원 한정)         6
속 깊은 디지털 라이프!                                        4
신한카드 스포츠누리로 보다 특별한 스포츠 할인 혜택을 누리세요!                  4
대중교통 10%할인, 커피전문점 20%할인, 4대백화점 및 3대 할인점 10%할인 3...   4
...                                                 ..
프리드라이프 상조회비 자동이체시 할인까지!                              1
교육훈련비 환급에 신한은행 혜택까지 모두 누리세요~                         1
대한민국 공무원만이 느끼는 자부심, 신한 공무원 연금카드                      1
속 깊은 당신을 위한 경차사랑 Life                                1
메가마트 포인트 1.5% 적립(점외 이용 시 0.5% 적립)                    1

[201 rows x 1 columns]

[소개]

                                    연회비
없음                                   81
해외겸용 7천원                              9
면제(해당 카드에 한해서 유효기간 동안 연회비 면제)         7
국내전용 5천원, 해외겸용 7천원                    4
1만원                                   4
...                                 ...
URS/UPI 2만 7천원\nVISA 3만원              1
면제\n(해당카드에 한해 유효기간 동안 연회비 면제)         1
VISA 10,000원(기본 5천원 + 서비스 5천원)        1
S& 1만원, 해외겸용 VISA 1만 3천원              1
국내전용 5천원 , 실버 7천원, Platinum 1만 5천원    1

[140 rows x 1 columns]

[연회비]

                                                    옵션
후불교통기능                                              18
후불교통가능                                              14
후불교통기능, 가족카드 발급가능                                   12
후불교통카드                                              11
후불교통 기능                                              5
...                                                 ..
서울, 경기, 인천, 부산, 대구, 충남,\n강원 거주자에 한하여 교통기능 탑재         1
신한 하이패스 행복카드 신규/추가 신청시, 2장의 카드(신용카드/후불하이패스카드)가 ...   1
IC기능 탑재(현금카드,전자통장, 공인인증서)\n후불교통기능                    1
후불교통 선택 가능                                           1
후불교통 기능 필수\n가족카드 발급 가능\n※ gallery S 카드는 VISA 브랜...   1

[107 rows x 1 columns]

[옵션]

                                 카드명
FC서울 유소년축구사랑 S카드 체크                3
S카드 스포츠누리 체크                       3
NCSOFT S카드 체크                      3
넥슨 메이플스토리 S카드 체크                   3
롯데시네마 대전/충청 직영관 S카드 S-Choice 체크    3
...                              ...
아이파크몰 WEEKI S카드 Big Plus GS칼텍스     1
S카드 B.Big(삑)                       1
장애인 통합복지 S카드 2030                  1
대한장례인협회 GS칼텍스 S카드 S                1
내미래 S카드 Simple Platinum#           1

[234 rows x 1 columns]

[카드명]

## crawling data load

In [7]:
# crawling 데이터1
data_crawling=pd.read_csv("./Card_crawl.csv", index_col=0, encoding='cp949')
data_crawling["카드명"]=Card_data["카드명"]
data_crawling.head()

,options,src,카드명
0,옵션후불교통가능가족카드발급불가온라인신청>간편신청>,"<img alt=""Master"" class=""shcd-card-type"" src=""...",한국야쿠르트 팝 S카드 체크
1,NaN,NaN,카카오페이 S 체크카드(무지)
2,간편신청>,"<img alt=""VISA"" class=""shcd-card-type"" src=""/i...",S카드 Deep Dream 체크
3,옵션후불교통가능,"<img alt=""Master"" class=""shcd-card-type"" src=""...",S카드 JYP Fan’s EDM 체크
4,NaN,NaN,S카드 Deep Dream 체크\n(미니언즈)

In [8]:
# crawling 데이터2
data2_crawling=pd.read_csv("./Card_crawl2.csv", index_col=0, encoding='cp949')
data2_crawling.head()

,카드명,options,src
0,카카오페이 S 체크카드(무지),카카오페이결제2%적립대중교통3%적립이동통신요금3%적립,"<img alt=""국내 카드"" src=""/pconts/images/contents/..."
1,S카드 Deep Dream 체크\n(미니언즈),전월실적/한도없이포인트적립주유적립택시할인신한금융그룹서비스수수료우대,"<img alt=""비자 카드"" src=""/pconts/images/contents/..."
2,S카드 Deep Dream 체크\n(미니언즈),전월실적/한도없이포인트적립주유적립택시할인신한금융그룹서비스수수료우대,"<img alt=""비자 카드"" src=""/pconts/images/contents/..."
3,해피포인트 S카드 BigPlus 체크,해피포인트가맹점내이용시최고20%청구할인,"<img alt=""VISA"" class=""shcd-card-type"" src=""/i..."
4,복리후생 우체국/제일/S/우리 S카드 BigPlus 체크,선택적복리후생용체크카드는소속사에서복리후생을적용하기위한임직원카드입니다.,"<img alt=""VISA"" class=""shcd-card-type"" src=""/i..."

In [9]:
# crawl1 + crawl2
for tt in range(len(data_crawling)):
    for t in range(len(data2_crawling)):
        if data_crawling['카드명'][tt] == data2_crawling['카드명'][t]:
            data_crawling['options'][tt] = data2_crawling['options'][t]
            data_crawling['src'][tt] = data2_crawling['src'][t]

In [10]:
# Card_data["Card_cp_crawl"]=data_crawling["src"]
# Card_data["Card_cp"]=np.where(pd.notnull(Card_data["Card_cp_crawl"])==True, Card_data["Card_cp_crawl"], Card_data["연회비"])
# Card_data.head()

In [11]:
Card_data["옵션_crawl"]=data_crawling["options"]
Card_data["옵션_notNA"]=np.where(pd.notnull(Card_data["옵션"])==True, Card_data["옵션"], Card_data["옵션_crawl"])
Card_data.head()

,Card_ID,분류,혜택분야,소개,연회비,옵션,카드명,옵션_crawl,옵션_notNA
0,0,체크카드,life,한국야쿠르트와 GS리테일의 특별한 혜택 !,없음,후불교통가능\n가족카드 발급 불가,한국야쿠르트 팝 S카드 체크,옵션후불교통가능가족카드발급불가온라인신청>간편신청>,후불교통가능\n가족카드 발급 불가
1,1,체크카드,life,카카오페이로 간편하게 결제하고 혜택까지 플러스,없음,후불교통가능\n가족카드 발급 불가,카카오페이 S 체크카드(무지),카카오페이결제2%적립대중교통3%적립이동통신요금3%적립,후불교통가능\n가족카드 발급 불가
2,2,체크카드,life,속 깊은 디지털 라이프!,없음,가족카드 가능,S카드 Deep Dream 체크,간편신청>,가족카드 가능
3,3,체크카드,life,난치병 아이들의 꿈을 이뤄주는 기부카드,없음,후불교통가능,S카드 JYP Fan’s EDM 체크,옵션후불교통가능,후불교통가능
4,4,체크카드,life,미니언즈가 다 드림!,없음,NaN,S카드 Deep Dream 체크\n(미니언즈),전월실적/한도없이포인트적립주유적립택시할인신한금융그룹서비스수수료우대,전월실적/한도없이포인트적립주유적립택시할인신한금융그룹서비스수수료우대

In [12]:
# 결측치 일부 크롤링으로 처리 후, 다시 결측치 확인
Card_data.isnull().sum()

Card_ID      0
분류           0
혜택분야         0
소개           0
연회비          0
옵션          58
카드명          0
옵션_crawl     8
옵션_notNA     1
dtype: int64

> 결측치 처리 결과, 옵션_notNA 결측치 1개로 줄임

In [13]:
# 최종 결측치 처리
Card_data["옵션_notNA"].fillna("옵션 없음", inplace=True)

## Option One-Hot-Encoding

In [14]:
data_opt=Card_data["옵션_notNA"]
list_=[0 for k in range(len(data_opt))]

# 후불교통 옵션 포함시 +1
for j in range(len(data_opt)):
    if "교통" in str(data_opt[j]):
        list_[j]+=1

# 불가시 -1           
for t in range(len(data_opt)):
    if "후불교통 불가" in str(data_opt[t]):
        list_[t]-=1           

opt_cnt=pd.DataFrame({'후불교통':list_})
Card_data["후불교통"]=opt_cnt

In [15]:
list_=[0 for k in range(len(data_opt))]
NO_family=["가족카드 발급 불가", "가족카드 불가", "가족카드불가"]

# 가족카드 옵션 포함시 +1
for j in range(len(data_opt)):
    if "가족" in str(data_opt[j]):
        list_[j]+=1

# 불가시 -1           
for t in range(len(data_opt)):
    for no in NO_family:
        if no in str(data_opt[t]):
            list_[t]-=1            

opt_cnt=pd.DataFrame({'가족카드':list_})
Card_data["가족카드"]=opt_cnt

In [16]:
list_=[0 for k in range(len(data_opt))]

# 현금기능 옵션 포함시 +1
for j in range(len(data_opt)):
    if "현금" in str(data_opt[j]):
        list_[j]+=1

# 불가시 -1           
for t in range(len(data_opt)):
    if "현금기능 불가" in str(data_opt[t]):
        list_[t]-=1          

opt_cnt=pd.DataFrame({'현금기능':list_})
Card_data["현금기능"]=opt_cnt

In [17]:
list_=[0 for k in range(len(data_opt))]

# IC기능 옵션 포함시 +1
for j in range(len(data_opt)):
    if "IC" in str(data_opt[j]):
        list_[j]+=1       

opt_cnt=pd.DataFrame({'IC기능':list_})
Card_data["IC기능"]=opt_cnt

In [18]:
Card_data.head()

,Card_ID,분류,혜택분야,소개,연회비,옵션,카드명,옵션_crawl,옵션_notNA,후불교통,가족카드,현금기능,IC기능
0,0,체크카드,life,한국야쿠르트와 GS리테일의 특별한 혜택 !,없음,후불교통가능\n가족카드 발급 불가,한국야쿠르트 팝 S카드 체크,옵션후불교통가능가족카드발급불가온라인신청>간편신청>,후불교통가능\n가족카드 발급 불가,1,0,0,0
1,1,체크카드,life,카카오페이로 간편하게 결제하고 혜택까지 플러스,없음,후불교통가능\n가족카드 발급 불가,카카오페이 S 체크카드(무지),카카오페이결제2%적립대중교통3%적립이동통신요금3%적립,후불교통가능\n가족카드 발급 불가,1,0,0,0
2,2,체크카드,life,속 깊은 디지털 라이프!,없음,가족카드 가능,S카드 Deep Dream 체크,간편신청>,가족카드 가능,0,1,0,0
3,3,체크카드,life,난치병 아이들의 꿈을 이뤄주는 기부카드,없음,후불교통가능,S카드 JYP Fan’s EDM 체크,옵션후불교통가능,후불교통가능,1,0,0,0
4,4,체크카드,life,미니언즈가 다 드림!,없음,NaN,S카드 Deep Dream 체크\n(미니언즈),전월실적/한도없이포인트적립주유적립택시할인신한금융그룹서비스수수료우대,전월실적/한도없이포인트적립주유적립택시할인신한금융그룹서비스수수료우대,0,0,0,0

In [19]:
# 필요없는 column 제거
Card_data.drop(['옵션', '옵션_crawl', '옵션_notNA', '소개', '연회비'], axis = 1, inplace = True)

## 최종 결측치 확인

In [20]:
Card_data.isnull().sum()

Card_ID    0
분류         0
혜택분야       0
카드명        0
후불교통       0
가족카드       0
현금기능       0
IC기능       0
dtype: int64

In [21]:
Card_data.head()

   Card_ID    분류  혜택분야                        카드명  후불교통  가족카드  현금기능  IC기능
0        0  체크카드  life            한국야쿠르트 팝 S카드 체크     1     0     0     0
1        1  체크카드  life           카카오페이 S 체크카드(무지)     1     0     0     0
2        2  체크카드  life          S카드 Deep Dream 체크     0     1     0     0
3        3  체크카드  life       S카드 JYP Fan’s EDM 체크     1     0     0     0
4        4  체크카드  life  S카드 Deep Dream 체크\n(미니언즈)     0     0     0     0

## 최종 Card_data 저장

In [22]:
Card_data.to_csv("Card_data.csv", encoding="cp949", index=False)